name: Build Windows EXE

on:
  workflow_dispatch:  # Lets you manually trigger the build from GitHub Actions tab

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build EXE for Windows
        run: npm run dist:win

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: railway-control-hmi-windows
          path: dist/*.exe
